site_name: Equções horárias

theme:
  name: mkdocs
  color_mode: dark
  user_color_mode_toggle: auto


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - glightbox